### Shorten a URL
POST http://localhost:5000/api/shorten
Content-Type: application/json

{
  "url": "https://www.google.com"
}

### Redirect (replace abc123 with your code)

//{
//  "short_code": "CKMd6y",
//  "short_url": "http://localhost:5000/CKMd6y"
//}

# GET http://localhost:5000/abc123


GET http://localhost:5000/CKMd6y


### Get stats
// GET http://localhost:5000/api/stats/abc123
GET http://localhost:5000/api/stats/CKMd6y
